### ISSUE TITLE
Feat: 기록 시 Firebase에 저장

### ISSUE THREAD

**Issue by LutherCho** [Good-MoGong/SYM#102]
## 📬 Issue: FEATURE

기록 시 Firebase에 저장
### 📃 Description

로그인 후 기록 시 Firebase 해당 아이디 하위 컬럼 Diary에 데이터 저장

### 🧪 Todo

- [x] 로그인 id 받아오기
- [x] 기록시 CoreData에 저장과 동시에 Firebase에 저장
- [x] 둘다 완료시 완료화면 나오게하기
