### ISSUE TITLE
ALL: 에러 발견시 기록해주세요.

### ISSUE THREAD

**Issue by syss220211** [Good-MoGong/SYM#113]
### 🧪 Todo
- [x] TextEditor 첫글자 입력시 키보드 내려가는 현상 (서연)
- [x] 탭바 사이즈 (서연)
- [x] localization, 라이트모드 설정하기 (서연)
- [x] 200글자 넘어도 입력되는 TextEditor (서연)
- [x] 기록하기뷰 뒤로가기 이상함
- [x] 기록하기뷰 키패드 올라올 때 버튼 가림
- [x] 기록하기뷰 다른 화면 터치시 화면 내려가도록 수정
- [x] 홈화면 스크롤 시 상단문구 고정하기
- [x] 기록하기뷰 실기기에서 탭바 나오는 현상
- [x] 기록후 기록보기 버튼 안눌리는 현상

<br>
