### ISSUE TITLE
Fix: 회원가입 분기처리 및 앱 삭제 시 토큰 처리

### ISSUE THREAD

**Issue by syss220211** [Good-MoGong/SYM#120]
### 📃 Description

- 닉네임을 입력하지 않고 다시 앱을 켰을 때, 다시 닉네임을 입력하는 뷰로 돌아오도록 구현하기
- 앱 삭제 시, 애플 토큰 관련 발생하는 에러 체킹

### 🧪 Todo

- [x] 닉네임 -> 기존에 있던 userdefault 활용하기
- [x] 애플 로그인 -> 토큰 재발행까지 5분이라는 텀이 있기때문에 발생하는 에러임!! 해결 완료
- [x] 로그아웃 후 바로 재로그인할 때 닉네임 패치 안 되는 오류
