### ISSUE TITLE
Refactor: gpt 응답 저장 및 작성내용 보기에 추가

### ISSUE THREAD

**Issue by OzDevelop** [Good-MoGong/SYM#130]
### 📃 Description

* gpt응답을 저장하는 부분과 관련된 작업을 진행합니다

### 🧪 Todo

- [x] gpt 응답 파이어베이스에 저장
- [x] gpt 응답 코어데이터 저장
- [x] 기록보기 뷰에 gpt응답 메시지 표시
