### ISSUE TITLE
Refactor: TextEditor 안눌림 해결, gpt응답메시지 Completion -> Combine으로 리팩토링, 기록보기 뷰 뒤로가기 제스처 가능

### ISSUE THREAD

**Issue by LutherCho** [Good-MoGong/SYM#135]
## 📬 Issue: FEATURE

Refact: TextEditor 안눌림 해결, gpt응답메시지 Completion -> Combine으로 리팩토링, 기록보기 뷰 뒤로가기 제스처 가능
### 📃 Description

1. TextEditor 안눌림 문제 해결
2. gpt응답 repository에서 completion으로 받던거 Combine으로 리팩토링
3. 기록보기 뷰 뒤로가기 제스처

### 🧪 Todo

- [x] TextEditor 안눌림 문제 해결
- [x] gpt응답 repository에서 completion으로 받던거 Combine으로 리팩토링
- [x] 기록보기 뷰 뒤로가기 제스처
