### ISSUE TITLE
Fix: 프로그래스뷰 버그 해결

### ISSUE THREAD

**Issue by OzDevelop** [Good-MoGong/SYM#137]
## 📬 Issue: FEATURE

루터님이 공유해주신 내용을 보니까 gpt 응답을 기다리는 프로그래스 뷰가 이상하게 그려짐.......

### 📃 Description

gpt 프로그레스 뷰 버그 해결

### 🧪 Todo

- [ ] 프로그레스 뷰 버그 해결
- [x] 카드뷰 분리로 인해서 마이페이지 전용 뷰 만들기
- [ ] 기록에서 데이터 수정 시 gpt 응답이 사라지는 문제

**Comment by syss220211** [comment]
@OzDevelop 해당 이슈 완료 됐나여?

**Comment by OzDevelop** [comment]
> @syss220211  해당 이슈 완료 됐나여?

넵 닫겠습니다
