### ISSUE TITLE
Style: 디자인 수정

### ISSUE THREAD

**Issue by LutherCho** [Good-MoGong/SYM#158]
## 📬 Issue: FEATURE

Style: 디자인 수정
### 📃 Description

디자인 수정할것들 넣어주세요.

### 🧪 Todo

- [x] CalendarRecordView: frame 지정
- [x] CalendarRecordView: Text 글씨 크기 줄임
- [x] CalendarRecordView: 이미지 변경
- [x] EmotionButton: height 줄임
- [x] emotionSelectView: Text 글씨 크기 줄임
- [x] RecordStartView: 이미지 크기 수정
- [x] TabBarView: 아이콘 프레임 수정
- [x] TabBarView: 프레임 수정
