### ISSUE TITLE
Fix: 피드백 사항 반영

### ISSUE THREAD

**Issue by syss220211** [Good-MoGong/SYM#169]
### 📃 Description

- 피드백 받은 사항 중 로그인 및 애니메이션 관련 에러 수정

### 🧪 Todo

- [ ]  회원가입 탈퇴 오류 수정
- [x]  애니메이션 시간 조정
- [x]  닉네임 입력시 공백 입력 막기
