### ISSUE TITLE
Feat: 캘린더 뷰 구현

### ISSUE THREAD

**Issue by a-jb97** [Good-MoGong/SYM#43]
### 📃 Description
- 민석, 지영 작업
- 캘린더 뷰 파트 구현

### 🧪 Todo
- [ ] 커스텀 캘린더 구현
- [ ] 오늘의 기록이 아직 없을 때의 뷰 구현
- [ ] 오늘의 기록이 있을 때의 모달(Sheet) 구현
