### ISSUE TITLE
Feat: CoreData 생성, CoreData 템플릿 생성, 기록하기 뷰 클린아키텍처 적용

### ISSUE THREAD

**Issue by LutherCho** [Good-MoGong/SYM#76]
## 📬 Issue: FEATURE
CoreData 생성, CoreData 템플릿 생성, 기록하기 뷰 클린아키텍처 적용

### 📃 Description
CoreData 데이터모델 생성
CoreData 템플릿(저장,수정,삭제,조회) 생성
기록하기 뷰 클린아키텍처 적용

### 🧪 Todo

- [x] CoreData 데이터모델 생성
- [x] CoreData 템플릿 생성
- [x] 기록하기 뷰 클린아키텍처 적용
