### ISSUE TITLE
Feat: 홈뷰(캘린더뷰) 데이터 fetch

### ISSUE THREAD

**Issue by yyomzzi** [Good-MoGong/SYM#85]
## 📬 Issue: FEATURE

- 캘린더뷰에 해당 날짜의 Diary fetch

### 📃 Description

- 코어데이터에 저장된 해당 날짜에 대한 Diary 데이터 fetch를 합니다.
- 캘린더뷰의 UI 작업을 마무리 합니다.

### 🧪 Todo

- [x] CalendarViewModel에 fetch 함수 구현
- [x] 캘린더뷰 배경 넣기
- [x] Diary 해당 날짜에 있으면 날짜에 red dot 표시
- [x] 감정 기록하기 버튼 탭하면 RecordStartView로 넘어가기
