### ISSUE TITLE
Feat: 카카오 및 애플 탈퇴 기능 구현

### ISSUE THREAD

**Issue by syss220211** [Good-MoGong/SYM#94]
### 📃 Description
- #92 에 명시된 순서대로 구현하겠습니다.
- 이번주 주말 작업 예정

### 🧪 Todo

- [x] 카카오 탈퇴
- [x] 애플 탈퇴
- [x] 로그인 뷰 수정
- [x] 마이페이지 Setting.swift 의 탈퇴 버튼에 로직 추가 (상필 작업 후 작업 예정)
- [x] firebase에서 Diary 컬렉션 데이터 날리기
- [x] 로그인 / 로그아웃에 progressview 추가
